### ISSUE TITLE
missing "DVS Decision Operation" in run configurations

### ISSUE THREAD

**Issue by dhpalan** [ODMDev/ruledesigner#10]
I installed Rule designer by following the Procedure given here.
https://www.ibm.com/support/knowledgecenter/en/SSQP76_8.10.x/com.ibm.odm.kube/topics/tsk_install_designer.html

1. Installed Oxygen.3a (4.7.3a)
2. Installed 8.10.3 - Rule Designer --> https://marketplace.eclipse.org/content/ibm-operational-decision-manager-developers-v-8103-rule-designer

We observed that the Rule designer is missing `DVS (Decision Validation Services)` launch configurations. 
Whereas the Rule designer 8.10.3 that was installed using `IBM Instalalltion manager` does contain DVS launch configurations.

**Comment by dhpalan** [comment]
I have attached a side-by-side comparison of rule designer launch configurations when installed from eclipse marketplace vs when installed from installation CD.
We couldn't figure out why there is a difference.

![image](https://user-images.githubusercontent.com/46791526/82848539-306ed480-9ef4-11ea-8b56-e60639a4d185.png)

**Comment by lgrateau** [comment]
It's a limitation of this Rule Designer version : 
https://www.ibm.com/support/knowledgecenter/en/SSQP76_8.10.x/com.ibm.odm.kube/topics/con_limitations.html
Decision Validation Services (DVS) in the Decision Center Enterprise console and in Rule Designer.

**Comment by dhpalan** [comment]
Thanks for your response. Could you please also comment on launch configuration called `Testing Decision Operation` ? 
We found that this is missing as well in the Rule Designer from marketplace.

Apparently we were trying to follow the instructions from here.
https://www.ibm.com/support/knowledgecenter/SSQP76_8.10.x/com.ibm.odm.dserver.rules.designer.test/topics/tsk_simple_test_ruleset_rd.html

**Comment by dhpalan** [comment]
@lgrateau  Thanks for your response. 
Could you please also comment on launch configuration called `Testing Decision Operation` ?
We found that this is missing as well in the Rule Designer from marketplace.

Apparently we were trying to follow the instructions from here.
https://www.ibm.com/support/knowledgecenter/SSQP76_8.10.x/com.ibm.odm.dserver.rules.designer.test/topics/tsk_simple_test_ruleset_rd.html
