### ISSUE TITLE
Unable to install any version of Rule Designer on Eclipse

### ISSUE THREAD

**Issue by TOttun** [ODMDev/ruledesigner#13]
Hi,

I have tried to install all versions of Rule Designer on my Eclipse and I get the following message

Cannot complete the install because one or more required items could not be found.
  Software being installed: IBM ODM for Developers - Rule Designer 8.10.5.1 (com.ibm.rules.studio.container.feature.feature.group 8.10.5.1)
  Missing requirement: IBM Decision Server Designer Base 8.10.5.1 (com.ibm.rules.studio.base.feature.feature.group 8.10.5.1) 
  requires 'org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.7.0,4.8.0)' but it could not be found
  Cannot satisfy dependency:
    From: IBM ODM for Developers - Rule Designer 8.10.5.1 (com.ibm.rules.studio.container.feature.feature.group 8.10.5.1)
    To: org.eclipse.equinox.p2.iu; com.ibm.rules.studio.base.feature.feature.group 0.0.0

My Eclipse version are below 

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2021-09 (4.21.0)
Build id: 20210910-1417
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 16.0.2+7-67
Java version: 16.0.2

**Comment by lgrateau** [comment]
@TOttun We only support Java 8 could you tried with that version and retry. 
Could you explain how to reproduce the issue ?
    - What do you use as Eclipse Version ? - You should use Eclipse 4.7.3 Oxygen Packages.
    - How do you installed Rule Designer : from Eclipse Market place or install site ?
   Thanks

**Comment by TOttun** [comment]
We only support Java 8 could you tried with that version and retry. - download Java8 from eclipse or on my system ?

Could you explain how to reproduce the issue ? - I tried downloading different versions of rule designer on eclipse none of them worked

- What do you use as Eclipse Version ? - Eclipse IDE 2021‑09, https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2021-09/R/eclipse-inst-jre-win64.exe

- How do you installed Rule Designer : from Eclipse Market place and I also tried using install new software in the help tab on eclipse

**Comment by lgrateau** [comment]
Thanks @TOttun  ,
Only the Eclipse 4.7.3 Oxygen Packages is supported. You can find the supported version by ODM version here: https://github.com/ODMDev/ruledesigner
Could you tried with that Eclipse Version ?

**Comment by TOttun** [comment]
can you send the version of eclipse ? I don't see it on their site

**Comment by lgrateau** [comment]
Yes. https://www.eclipse.org/downloads/packages/release/oxygen/3a/eclipse-ide-java-ee-developers this one. 
it should be Oxygen 3A

**Comment by TOttun** [comment]
will get back to you on this, thanks

**Comment by lgrateau** [comment]
yw let me know if we can close this issue.

**Comment by TOttun** [comment]
works now cheers
