### ISSUE TITLE
Eclipse Luna 4.4 is no longer supported

### ISSUE THREAD

**Issue by DTHompson55** [ODMDev/ruledesigner#2]
Eclipse Luna 4.4 is no longer supported, and does not open on the latest MacOS High Sierra 10.13.6 and Java jdk 1.8.0_181

**Comment by lgrateau** [comment]
Hi Daniel, we have added the update of Eclipse in our backlog.
Concerning your issue on MacOS High Sierra, i have exactly the same configuration and not encountered any issue.
Could you describe a little bit what happen ?

**Comment by lgrateau** [comment]
The 8.10.0 Release support  Eclipse 4.7 Oxygen Packages

**Comment by lgrateau** [comment]
https://github.com/ODMDev/ruledesigner/tree/8.10.0
