### ISSUE TITLE
Unable to read repository

### ISSUE THREAD

**Issue by piyabisht** [ODMDev/ruledesigner#4]
I'm unable to install new software for rule designer from github URl.
Its returning issue that unable to read respository.

https://raw.githubusercontent.com/ODMDev/ruledesigner/2018.12-ooc/p2

**Comment by cleclerc75** [comment]
Hello piyabisht, 

I just installed successfully Rule Designer for an ODM on Cloud 2018.12 subscription (SaaS offer exclusively). The repository is accessible but not directly within a browser or by adding content.xml in your url only as below: 
https://raw.githubusercontent.com/ODMDev/ruledesigner/2018.12-ooc/p2/content.xml
Could you provide more details if you still notice an issue ?
Hope this helps,
--
Christian Leclerc

**Comment by piyabisht** [comment]
Hi Christian,
Thank you for answering. I'm still facing issue while installing rule designer from eclipse marketplace. If i'm trying to install rule designer through instructions mentioned above. It is showing error and installation is failing. 
Could you please assist. 
Error is  - Unable to read repository at https://raw.githubusercontent.com/ODMDev/ruledesigner/8.9.2/p2/content.xml

Regards,
Priya Bisht

**Comment by cleclerc75** [comment]
Hello Priya,

In your second URL, you are not refering to ODM on Cloud (the SaaS offer for ODM) but to a classical on Prem installation: https://raw.githubusercontent.com/ODMDev/ruledesigner/8.9.2/p2/content.xml 
ODM on Cloud doesn't need the same Designer as ODM on Prem. I know well ODM on Cloud (SaaS) requirements but less other ODM usage/product. Could you clarify what you are trying to do ? 

From ODM 8.10.0, Eclipse requirements have changed. You need to install Eclipse Oxygen
Whereas with previous ODM versions, you need Eclipse Luna. 
Could you have a look to your Eclipse About section, please and share here your finding ? 

Regards,
Christian Leclerc

**Comment by piyabisht** [comment]
Hi Christian,
ODM on cloud installation has been completed. Now I'm installing ODM on Prem and referring to this URL: https://raw.githubusercontent.com/ODMDev/ruledesigner/8.9.2/p2/content.xml

I'm using Eclipse Luna 4.4.0 and trying to install rule designer version 8.9.2 from Eclipse Marketplace.
Please let me know if you need any further details.

Thanks,
Priya Bisht

**Comment by TAMILSELVANP** [comment]
I too face the same issue, below is the error am getting,

Unable to read repository at https://raw.githubusercontent.com/ODMDev/ruledesigner/8.9.2/p2/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
